name: test

on:
  workflow_dispatch:
  workflow_run:
    workflows: [ linux-x64 ]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get latest sby sources
        uses: actions/checkout@v4
        with:
          repository: YosysHQ/sby
      - name: Setup test environment
        uses: YosysHQ/setup-oss-cad-suite@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          python-override: true
      - name: Run checks
        run: tabbypip install xmlschema && make ci
